/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  
        //ACTIONS
        PLAY("[object][PLAY]",1500),
        NEXT("[object][NEXT]", 1500),
        PREV("[object][PREV]", 1500),
        PAUSE("[object][PAUSE]",1500),
        RESUME("[object][RESUME]",1500),
        VOLUP("[object][VOLUP]",1500),
        FAST("[object][FAST]",1500),
        VOLDOWN("[object][VOLDOWN]",1500),
        SLOW("[object][SLOW]",1500),
        REPEATON("[object][REPEATON]",1500),
        REPEATOFF("[object][REPEATOFF]",1500),
        RANDOMON("[object][RANDOMON]",1500),
        RANDOMOFF("[object][RANDOMOFF]",1500),
        QUIT("[object][QUIT]",1500),
        MUTE("[object][MUTE]",1500),
        SPEAK("[object][SPEAK]",1500),
        MUSIC_NAME("[object][MUSIC_NAME]",1500),
        TIME_MUSIC("[object][TIME_MUSIC]",1500),
        FULLNUMBER("[fullnumber]", 1500);
        


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
